from src.modules.servermenu.menu                   import servermenu
from src.modules.tokenmenu.menu                    import tokenmenu
from src.modules.spammingmenu.menu                 import spammingmenu
from src.modules.bypassmenu.menu                   import bypassmenu
from src.modules.vcmenu.menu                       import vcmenu
from src.modules.webhookmenu.menu                  import webhookmenu
from src.modules.nukingmenu.menu                   import nukingmenu
from src.modules.proxymenu.menu                    import proxymenu
from src.modules.massdmmenu.menu                   import massdmmenu
from src.modules.massreportmenu.menu               import massreportmenu
from src.modules.annoyingmenu.menu                 import annoyingmenu
from src.modules.funnymenu.menu                    import funnymenu
from src.modules.advertisingmenu.menu              import advertisingmenu
from src.modules.boostingmenu.menu                 import boostingmenu
from src.modules.sources                           import sources